export const aboutMessage = {
  BASIC_INFORMATION: 'Basic information successfully added.',
  PHONE_NUMBER_UPDATE: 'Phone number updated successfully.',
  EMAIL_UPDATE: 'Email updated successfully.',
  COMMUNITIES_SERVED: 'Communities served successfully added.',
  COMMUNITIES_SERVED_VALIDATION: 'Communities served details is required',
  TAGS_FOR_FILTER_SUCCESS: 'Tags for filter successfully added.',
  TAGS_FOR_FILTER_VALIDATION: 'Tags for filter details are required',
  FETCH_DATA: 'User details fetched successfully.',
  UPDATED_SUCCESSFULLY: 'User details updated successfully.',
  CREATE_SUCCESSFULLY: 'User details created successfully.',
  GALLERY_UPDATED_SUCCESSFULLY: 'Gallery item updated successfully',
  PROFILE_UPDATED_SUCCESSFULLY: 'Profile image updated successfully',
  GALLERY_DELETE_SUCCESSFULLY: 'Gallery item removed successfully',
  LOCATION_UPDATED_SUCCESSFULLY: 'Location successfully added',
  AVAILABILITY_UPDATED_SUCCESSFULLY: 'Availability data successfully added',
  PRIMARY_CREDENTIAL_ADD_SUCCESSFULLY: 'Primary credentials added successfully',
  FINANCE_UPDATED_SUCCESSFULLY: 'Finance successfully added',
  EDUCATION_UPDATED_SUCCESSFULLY: 'Education successfully added',
  URL_CREATE_SUCCESSFULLY: 'Add link updated successfully',
  PASSWORD_UPDATED: 'User password updated successfully',
  PROFESSIONAL_INSURANCE_UPDATED: 'User NPI & Professional insurance updated successfully',
  PRIMARY_CREDENTIAL_UPDATED: 'Primary credentials updated successfully',
  FOLLOW_PROVIDER_UPDATED: 'Followed User Successfully',
  UNFOLLOW_PROVIDER_UPDATED: 'UnFollowed User Successfully',
  USER_NOT_FOUND: 'User not found',
  PLAN_NOT_FOUND: 'Plan not found',
  PROVIDER_NOT_FOUND: 'Provider not found',
  CLIENT_NOT_FOUND: 'Client not found',
  PASSWORD_CHANGE: 'New password cannot be the same as the current password',
  CHECK_CURRENT_PASSWORD: 'Current password is incorrect',

  INVALID_USER: 'Invalid user',
  PASSWORD_NOT_MATCH: 'Passwords do not match',
  NOT_FOUND: 'User details not found',
  PAYMENT_UNSUCCESSFUL: 'Payment was not successful.',
  LINK_DELETED:'Link deleted successfully',
  PARENTAL_SETTINGS_UPDATE: 'Parental settings updated successfully',
  PARENTAL_SETTINGS_LIST: 'Parental settings fetched successfully',
  DEACTIVATED_SUCCESS: 'Account has been deactivated',
  EMAIL_VALIDATION: 'This email is already exist',
  ADDITIONAL_EMAIL_VALIDATION: 'Additional email is already exist',
  SAME_EMAIL_VALIDATION: 'The new email is the same as the current email. Please provide a different email address.',
  ACTIVE_LINKS_DATA: 'Active links fetched successful',
  CLINICAL_SPECIALITES: 'Clinical specialities fetched successful',
  CLINICAL_UPDATE_SPECIALITES:'Clinical specialities updated successful',
  TREATMENT_MODALITIES_UPDATE:'Treatment modalities updated successful',
  TREATMENT_MODALITIES_DATA: 'Treatment modalities fetched successful',
  SHARED_EXPERIENCES_UPDATE:'Shared experience updated successful',
  SHARED_EXPERIENCES_DATA: 'Shared experiences fetched successful',
  PRIMARY_CREDENTIALS_DATA: 'Primary credentials fetched successful',
  BROAD_CERTIFICATE_UPDATE:'Broad certificate updated successful',
  BROAD_CERTIFICATE_CREATE:'Broad certificate created successful',
  INTERNSHIP_CREATE:'Internship created successful',
  INTERNSHIP_UPDATE:'Internship details updated successfully.',
  RESIDENCY_CREATE:'Residency created successful',
  RESIDENCY_UPDATE:'Residency information updated successfully.',
  FELLOW_SHIP_CREATE:'Fellow ships created successful',
  FELLOW_SHIP_UPDATE:'Fellowships updated successfully.',
  URL_UPDATE:'URL updated successfully.',
  DELETE_GALLERY_ID_CHECK:'Id is require',
  MY_IDENTITY_UPDATE: 'Identity updated successfully',
  PLAN_ID_VALIDATION:'Plan id is required',
  WALLET_BALANCE_VALIDATION:'Your wallet balance is insufficient',
  IMAGE_FILE_VALIDATION:'At least one file is required for upload',
  IMAGE_FILE_FORMATE_VALIDATION:'Only .png, .jpg and .jpeg formats are allowed!',
  EDUCATION_UPDATE:'Education updated successfully.',
  EDUCATION_CREATE:'Education created successfully.',
  LICENSE_DELETE_DOCUMENTS:'License image deleted successfully',
  LICENSE_UPLOAD_DOCUMENTS:'License document uploaded successfully',
  EMAIL_ALREADY_EXIST:'Email already exists',
  FOLLOWER_LIST:'Follower list fetched successfully',
  PROVIDER_LIST:'Provider list fetched successfully',

  PROVIDER_SUBSCRIBED_SUCCESSFULLY: 'Subcribed to provider successfully',
  PAUSED_PROVIDER_SUBSCRIPTION: 'Paused provider subscription',
  RESUMED_PROVIDER_SUBSCRIPTION: 'Resumed provider subscription',
  ONLY_CLIENT_CAN_SUBSCRIBE: "Only client can subscribe to provider",
  PROVIDER_SUBSCRIBED_LIST_SUCCESSFULLY: 'Subcribed providers list fetched successfully',
  SUBSCRIBED_CLIENT_LIST: 'Subcribed clients list fetched successfully',

}
